disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - function_parameter_count
opt_in_rules: # some rules are only opt-in

  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

  
variable_name:
  min_length: # only min_length
    warning: 1
    error: 1 # only error
    
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)