# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Nino' do
pod ‘SwiftKeychainWrapper’
end

target 'NinoTests' do

end

target 'NinoUITests' do

end

target 'Nino Escola' do

end

target 'Nino EscolaTests' do

end

target 'Nino EscolaUITests' do

end

