# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Nino' do
pod 'SwiftKeychainWrapper'
pod 'IQKeyboardManagerSwift', '4.0.0'
pod 'TOCropViewController'
pod 'QBImagePickerController'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'RealmSwift'
pod 'JWTDecode'
end

target 'NinoTests' do

end

target 'NinoUITests' do

end

target 'Nino Escola' do
pod 'SwiftKeychainWrapper'
pod 'TOCropViewController'
pod 'IQKeyboardManagerSwift', '4.0.0'
pod 'QBImagePickerController'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'RealmSwift'
pod 'JWTDecode'

# Chat
#pod 'QMChatViewController'
#pod 'QMServices'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'QuickBlox'
#Production pod

#For development pods

#Production pod

pod 'SearchEmojiOnString'
pod 'TagListView', '~> 1.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'BEMCheckBox'

end

target 'Nino EscolaTests' do
pod 'TagListView', '~> 1.0'
pod 'BEMCheckBox'
end

target 'Nino EscolaUITests' do
pod 'TagListView', '~> 1.0'
pod 'BEMCheckBox'
end

